name: 🐛 Bug Report
description: Report a bug or unexpected behavior in shadcn_flutter
title: "[Bug]: "
labels: [ "bug", "needs triage" ]
assignees: []
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

- type: textarea
  id: bug-description
  attributes:
    label: Bug Description
    description: A clear and concise description of what the bug is.
    placeholder: Describe the bug...
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
    placeholder: What should have happened?
  validations:
    required: true

- type: textarea
  id: actual-behavior
  attributes:
    label: Actual Behavior
    description: A clear and concise description of what actually happened.
    placeholder: What actually happened?
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Go to '...'
      2. Use component '...'
      3. Set property '...'
      4. See error
  validations:
    required: true

- type: dropdown
  id: component
  attributes:
    label: Which component is affected?
    description: Select the component that has the bug
    options:
    - Alert
    - AlertDialog
    - Avatar
    - Badge
    - Breadcrumb
    - Button
    - Calendar
    - Card
    - Carousel
    - Checkbox
    - Command
    - ContextMenu
    - DataTable
    - DatePicker
    - Dialog
    - Drawer
    - DropdownMenu
    - Form
    - HoverCard
    - Input
    - InputOTP
    - Label
    - Menubar
    - NavigationMenu
    - Pagination
    - Popover
    - Progress
    - RadioGroup
    - ScrollArea
    - Select
    - Separator
    - Sheet
    - Skeleton
    - Slider
    - Switch
    - Table
    - Tabs
    - Textarea
    - TimePicker
    - Toast
    - Toggle
    - Tooltip
    - Other/Multiple
  validations:
    required: true

- type: input
  id: flutter-version
  attributes:
    label: Flutter Version
    description: What version of Flutter are you using?
    placeholder: "flutter --version"
  validations:
    required: true

- type: input
  id: shadcn-version
  attributes:
    label: shadcn_flutter Version
    description: What version of shadcn_flutter are you using?
    placeholder: "Check pubspec.yaml"
  validations:
    required: true

- type: dropdown
  id: platform
  attributes:
    label: Platform
    description: Which platform(s) does this issue occur on?
    multiple: true
    options:
    - Android
    - iOS
    - Web
    - Windows
    - macOS
    - Linux
  validations:
    required: true

- type: textarea
  id: code-sample
  attributes:
    label: Minimal Code Sample
    description: Please provide a minimal code sample that reproduces the issue
    render: dart
    placeholder: |
      import 'package:flutter/material.dart';
      import 'package:shadcn_flutter/shadcn_flutter.dart';

      class BugExample extends StatelessWidget {
        @override
        Widget build(BuildContext context) {
          return // Your code here
        }
      }
  validations:
    required: true

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: Add any other context about the problem here, including screenshots, error logs, etc.
    placeholder: Any additional information that might help...

- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Please confirm the following
    options:
    - label: I have searched existing issues and this is not a duplicate
      required: true
    - label: I have provided a minimal code sample that reproduces the issue
      required: true
    - label: I am using the latest version of shadcn_flutter
      required: false
